### PR TITLE
Cleanup and optimize

### PR DESCRIPTION
**Pull request by seware74**
1) Removed unused ReadString global parameter
2) Changed function parameters of String type to pass by reference instead of by value (to eliminate the expense of copies being made on each function call)
3) removed 3 uses of abs() on local variables that could only be positive.
4) moved 3 uses of abs() outside of the while loop as the function only needed to be executed once, not once per loop iteration
5) I think that was it

### CODE REVIEW

**Comment by BarbourSmith** [comment]
From giving this a read through it looks fantastic. All the changes make sense, and they all seem like logical improvements.

When I compile it it doesn't respond to commands (as if the arduino serial port wasn't opened or as if it was stuck in a while loop). Even the initial print statements don't show up which is strange because those are the first lines of code to run.

From looking at the changes I can's see anything that could cause that behavior.

Do you have any thoughts on where to look?

**Comment by seware74** [comment]
I'll take a look this over lunch and again tonight...

The major changes made that I think would relate...

1) Removed the global ReadString variable (I saw it being intialized in
several places but never referenced otherwise) Could I have missed it being
used elsewhere? (I was using "atom project find" to locate references)
2) Passing the command string by reference to functions that use it. (since
it compiled I assume the C++ compiler for arduino supported "references")
If not, changing them to pointers would have the same effect.


Stuck in a loop... hmm

There were 3 (almost identical) while loops that were using the abs
function within the while... I removed the abs on the changing variable (as
it was only an incrementer) and moved the abs function on the "checked
against" variable out of the loop, so it would not be executed every time
around. My recollection is that these were all declared locally... if I
missed something that was changing them within the loop (besides the
incrementer) that could cause a stuck loop.

Let me peer into the abyss and see what pops out.

**Comment by seware74** [comment]
And in the watchdog I moved the intialization of the char variable used for
serial reading to outside the loop where it's used. (prevents new variable
creation on every iteration). If arduino has some scope oddities, that is
certainly core to the serial reading.. a long shot, but perhaps?

**Comment by seware74** [comment]
Also ( I think I missed mentiong this in the commit) ... I removed the
toUpperCase within the G1 and G38 function as these should have already
been upper case from the upper casing going on in the main loop.

**Comment by BarbourSmith** [comment]
From looking through, it seems like all of those changes make a lot of sense. Nothing popped out at me as an obvious cause.

**Comment by blurfl** [comment]
On my setup, these changes interfere with control of the right motor; the left and z seem normal. Restoring the release restores normal control.

**Comment by seware74** [comment]
Bar was having some issues as well though the changes were kinda (or kinda not it seems) benign. I think his issues were different though. 
 I'll see if I can spot it tonight but may need to wait until I have some hardware to test with myself. 
-------- Original message --------From: Scott Smith <notifications@github.com> Date: 5/30/17  6:54 PM  (GMT-06:00) To: MaslowCNC/Firmware <Firmware@noreply.github.com> Cc: seware74 <seware74@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MaslowCNC/Firmware] Cleanup and optimize (#235) 
On my setup, these changes interfere with control of the right motor; the left and z seem normal. Restoring the release restores normal control.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MaslowCNC/Firmware","title":"MaslowCNC/Firmware","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MaslowCNC/Firmware"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blurfl in #235: On my setup, these changes interfere with control of the right motor; the left and z seem normal. Restoring the release restores normal control."}],"action":{"name":"View Pull Request","url":"https://github.com/MaslowCNC/Firmware/pull/235#issuecomment-305041663"}}}

**Comment by seware74** [comment]
I found on the  [Arduino reference](https://www.arduino.cc/en/reference/abs) for the abs function that it may have some non-standard behavior, compared to usual usage in C.  See the following:

> Warning
> 
> Because of the way the abs() function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results.

So, I've fixed my original changes that "misued" abs, and a few other "misuses" I found elsewhere in the project, to accommodate this peculiarity. An update to the pull (with a few other changes) will be forthcoming in a few minutes. Curious if this fixes anything for you Scott \  Bar?

**Comment by blurfl** [comment]
I'll give it a whirl later this evening. Thanks for digging so deeply!

**Comment by seware74** [comment]
Also made the String references in the function parameters const so that the originals could not be modified inadvertently (now that they refer to the original).

**Comment by blurfl** [comment]
On a different topic, sort of, the Arduino IDE uses different formatting from that found in the Maslow source files. The Arduino 'Auto Format' command alters tabs, spacing, line endings, even parentheses spacing. We've been asked to take care when issuing a PR to only change the pertinent lines, so that git can keep track of who has changed what.
 For myself, I prefer the format that Arduino imposes. Maybe one day we can refactor the files with the Arduino formatting. For now, I understand the reason for the request and honor it.

**Comment by seware74** [comment]
I'm using the atom ide as instructed in the readme.  Is there a way to prevent what I presume is eol differences?
I've been using the ?w=1 parameter in github to ignore whitespace when comparing. But would sure be nice not to have to.  I have found a fix yet, but I'm brand new to atom. 
-------- Original message --------From: Scott Smith <notifications@github.com> Date: 5/30/17  9:12 PM  (GMT-06:00) To: MaslowCNC/Firmware <Firmware@noreply.github.com> Cc: seware74 <seware74@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MaslowCNC/Firmware] Cleanup and optimize (#235) 
On a different topic, sort of, the Arduino IDE uses different formatting from that found in the Maslow source files. The Arduino 'Auto Format' command alters tabs, spacing, line endings, even parentheses spacing. We've been asked to take care when issuing a PR to only change the pertinent lines, so that git can keep track of who has changed what.

 For myself, I prefer the format that Arduino imposes. Maybe one day we can refactor the files with the Arduino formatting. For now, I understand the reason for the request and honor it.



> On May 30, 2017, at 6:51 PM, seware74 <notifications@github.com> wrote:

> 

> I found on the Arduino reference for the abs function that it may have some non-standard behavior, compared to usual usage in C. See the following:

> 

> Warning

> 

> Because of the way the abs() function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results.

> 

> So, I've fixed my original changes that "misued" abs, and a few other "misuses" I found elsewhere in the project, to accommodate this peculiarity. An update to the pull (with a few other changes) will be forthcoming in a few minutes. Curious if this fixes anything for you Scott \ Bar?

> 

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.

> 



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MaslowCNC/Firmware","title":"MaslowCNC/Firmware","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MaslowCNC/Firmware"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blurfl in #235: On a different topic, sort of, the Arduino IDE uses different formatting from that found in the Maslow source files. The Arduino 'Auto Format' command alters tabs, spacing, line endings, even parentheses spacing. We've been asked to take care when issuing a PR to only change the pertinent lines, so that git can keep track of who has changed what.\n For myself, I prefer the format that Arduino imposes. Maybe one day we can refactor the files with the Arduino formatting. For now, I understand the reason for the request and honor it.\n\n\u003e On May 30, 2017, at 6:51 PM, seware74 \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e I found on the Arduino reference for the abs function that it may have some non-standard behavior, compared to usual usage in C. See the following:\n\u003e \n\u003e Warning\n\u003e \n\u003e Because of the way the abs() function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results.\n\u003e \n\u003e So, I've fixed my original changes that \"misued\" abs, and a few other \"misuses\" I found elsewhere in the project, to accommodate this peculiarity. An update to the pull (with a few other changes) will be forthcoming in a few minutes. Curious if this fixes anything for you Scott \\ Bar?\n\u003e \n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Pull Request","url":"https://github.com/MaslowCNC/Firmware/pull/235#issuecomment-305062227"}}}

**Comment by davidelang** [comment]
I would suggest doing a reformatting pull request immediatly after Bar cuts a 
release on wednesday so that there is less chance of causing inadvertent 
problems (or at least a better chance of catching them before the next release)

**Comment by seware74** [comment]
I think I found the culprit that is reformatting in atom. Mea culpa... 
-------- Original message --------From: Scott Smith <notifications@github.com> Date: 5/30/17  9:12 PM  (GMT-06:00) To: MaslowCNC/Firmware <Firmware@noreply.github.com> Cc: seware74 <seware74@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MaslowCNC/Firmware] Cleanup and optimize (#235) 
On a different topic, sort of, the Arduino IDE uses different formatting from that found in the Maslow source files. The Arduino 'Auto Format' command alters tabs, spacing, line endings, even parentheses spacing. We've been asked to take care when issuing a PR to only change the pertinent lines, so that git can keep track of who has changed what.

 For myself, I prefer the format that Arduino imposes. Maybe one day we can refactor the files with the Arduino formatting. For now, I understand the reason for the request and honor it.



> On May 30, 2017, at 6:51 PM, seware74 <notifications@github.com> wrote:

> 

> I found on the Arduino reference for the abs function that it may have some non-standard behavior, compared to usual usage in C. See the following:

> 

> Warning

> 

> Because of the way the abs() function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results.

> 

> So, I've fixed my original changes that "misued" abs, and a few other "misuses" I found elsewhere in the project, to accommodate this peculiarity. An update to the pull (with a few other changes) will be forthcoming in a few minutes. Curious if this fixes anything for you Scott \ Bar?

> 

> —

> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub, or mute the thread.

> 



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MaslowCNC/Firmware","title":"MaslowCNC/Firmware","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MaslowCNC/Firmware"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blurfl in #235: On a different topic, sort of, the Arduino IDE uses different formatting from that found in the Maslow source files. The Arduino 'Auto Format' command alters tabs, spacing, line endings, even parentheses spacing. We've been asked to take care when issuing a PR to only change the pertinent lines, so that git can keep track of who has changed what.\n For myself, I prefer the format that Arduino imposes. Maybe one day we can refactor the files with the Arduino formatting. For now, I understand the reason for the request and honor it.\n\n\u003e On May 30, 2017, at 6:51 PM, seware74 \u003cnotifications@github.com\u003e wrote:\n\u003e \n\u003e I found on the Arduino reference for the abs function that it may have some non-standard behavior, compared to usual usage in C. See the following:\n\u003e \n\u003e Warning\n\u003e \n\u003e Because of the way the abs() function is implemented, avoid using other functions inside the brackets, it may lead to incorrect results.\n\u003e \n\u003e So, I've fixed my original changes that \"misued\" abs, and a few other \"misuses\" I found elsewhere in the project, to accommodate this peculiarity. An update to the pull (with a few other changes) will be forthcoming in a few minutes. Curious if this fixes anything for you Scott \\ Bar?\n\u003e \n\u003e —\n\u003e You are receiving this because you commented.\n\u003e Reply to this email directly, view it on GitHub, or mute the thread.\n\u003e \n"}],"action":{"name":"View Pull Request","url":"https://github.com/MaslowCNC/Firmware/pull/235#issuecomment-305062227"}}}

**Comment by blurfl** [comment]
The readme lists four different editing environments. No doubt each will try to impose its own formatting if we're not careful.

**Comment by davidelang** [comment]
> The readme lists four different editing environments. No doubt each will try to impose its own formatting if we're not careful.

Yes, we need to pick one, switch to it and then enforce it.

I don't care that much which one. I have pet peeves, like anyone else, but 
having a standard is more important than which one it is.

**Comment by blurfl** [comment]
We can use the existing as the standard. We just need to avoid altering anything unintentionally.

**Comment by blurfl** [comment]
@seware74, I've downloaded and applied the changed files. They introduce an issue which causes repeated 'connection lost' messages to the console, a communication error but probably not a serial issue. Shifting back to the version of the PR from yesterday takes me back to the situation where communication is proper but my right motor does not operate.
 Restoring the Axis.cpp file did not change the communication issue. I spent some time trying to pin down the cause of the communication issue but ran out of time. Perhaps breaking apart the 'abs()' patches from the string patches wouldn isolate that. Because of the communication issue I wasn't able to determine whether the issue driving the motors had changed.
 Thanks for taking a deep dive into the firmware, the things you point out are worth exploring.

**Comment by seware74** [comment]
Very odd...but I agree. Certainly let's hold. When I have something in hand to test with besides a sim... I'll start again from the last known good and test each change type in isolation in its own branch.  
Would you like each change type as a separate PR so you guys can test in isolation also?

I'll also start with a fresh fork so the whitespace diffs won't be a problem.
Thanks for testing Scott. Bar you can kill the existing pull request... I'll work silently in the shadows until I can figure this out.

-------- Original message --------From: Scott Smith <notifications@github.com> Date: 5/31/17  12:39 AM  (GMT-06:00) To: MaslowCNC/Firmware <Firmware@noreply.github.com> Cc: seware74 <seware74@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [MaslowCNC/Firmware] Cleanup and optimize (#235) 
@seware74, I've downloaded and applied the changed files. They introduce an issue which causes repeated 'connection lost' messages to the console, a communication error but probably not a serial issue. Shifting back to the version of the PR from yesterday takes me back to the situation where communication is proper but my right motor does not operate.

Restoring the Axis.cpp file did not change the communication issue. I spent some time trying to pin down the cause of the communication issue but ran out of time. Perhaps breaking apart the 'abs()' patches from the string patches wouldn isolate that. Because of the communication issue I wasn't able to determine whether the issue driving the motors had changed.

Thanks for taking a deep dive into the firmware, the things you point out are worth exploring.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MaslowCNC/Firmware","title":"MaslowCNC/Firmware","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MaslowCNC/Firmware"}},"updates":{"snippets":[{"icon":"PERSON","message":"@blurfl in #235: @seware74, I've downloaded and applied the changed files. They introduce an issue which causes repeated 'connection lost' messages to the console, a communication error but probably not a serial issue. Shifting back to the version of the PR from yesterday takes me back to the situation where communication is proper but my right motor does not operate.\r\n Restoring the Axis.cpp file did not change the communication issue. I spent some time trying to pin down the cause of the communication issue but ran out of time. Perhaps breaking apart the 'abs()' patches from the string patches wouldn isolate that. Because of the communication issue I wasn't able to determine whether the issue driving the motors had changed.\r\n Thanks for taking a deep dive into the firmware, the things you point out are worth exploring."}],"action":{"name":"View Pull Request","url":"https://github.com/MaslowCNC/Firmware/pull/235#issuecomment-305088754"}}}

**Comment by BarbourSmith** [comment]
Ok, I'll close this one, but I think these are all still good ideas that I don't want to see slip away.

I think making each type of change as a different pull request is a great idea. That would make it easy for us to test.

There is also an Arduino winging it's way to you which will help.

**Comment by davidelang** [comment]
If not a separate pull request, at least a separate commit within the pull 
request. That way we could use git bisect to walk through the different changes 
and identify which one was the problem

**Pull request closed without merging**
