### PR TITLE
Support zAxisAuto settings from GroundControl (B12 Y)

### PR DESCRIPTION
**Pull request by skiz**
Firmware update that allows setting the AUX1 to to be active high for supporting M codes based on `B12 Y`

### CODE REVIEW

**Comment by blurfl** [comment]
How about moving the pin definition up to the top where the AUX pins are defined, so it's clear which pins have been committed? AUX4 is the z-axis depth probe presently. When moving the definition out of the function, maybe name spindleControlPin would be better?

**Comment by skiz** [comment]
@blurfl AUX1 has already been committed, and I just made the existing code configurable.  AUX1 has 2 different usages depending on the configuration (servo signal vs 5v).  I'll clean this up a bit.

**Comment by BarbourSmith** [comment]
@blurfl you have the most in depth knowledge of this section of code, thank you for taking a look at it. Does it look ready to merge to you?

@skiz Thank you for all of these improvements! What a cool thing to see first thing on a Monday morning 😀

**Comment by blurfl** [comment]
It looks good. Thanks for cleaning up the AUX4 definition as well. Ship it!

**Pull request merged**
