### PR TITLE
Add PWM frequency to system settings

### PR DESCRIPTION
**Pull request by blurfl**
This builds upon PR #385 and #386 to allow changing the PWM prescaler frequency from GroundControl.

This needs a cooresponding GroundControl PR (GroundControl #619).

 - add a system setting $39 fPWM
 - set the default value to 3 = 490Hz
 - change the prescaler for timers2-4 on change of fPWM
 - report the change if verboseDebug > 0

### CODE REVIEW

**Comment by krkeegan** [comment]
You also need to increment the SettingsVersion number in settings.h as well.  This ensures that settings on the arduino are wiped and reloaded with the default and then loaded from GC.  Otherwise, the new variable or potentially other variables can have some very odd values or even overflows.

**Comment by blurfl** [comment]
Interesting, you can change PWM frequency within a cut file using $39=  commands. 
$39=1 -> 31,000Hz    $39=2 -> 4,100Hz    $39=3 -> 490Hz
Most changes seem pretty benign, though changing fPWM into 4,100Hz causes quite a lag sometimes. Probably not something to be used in every-day cutting, but interesting to use while exploring 😀.

**Comment by blurfl** [comment]
it seems like the lag can happen with  any speed change during a cut, but putting in a manual z-axis change (or a several-second long auto one) seems to give the affected routine (PID?) time to clear or catch up. Not that a speed change would be useful, but it does cast interesting shadows of some internal process.

**Comment by blurfl** [comment]
To see it change, turn on 'verboseDebug' in Config.h...

**Comment by BarbourSmith** [comment]
This is so mind blowing. Wow. I want to keep playing around with it more, but even just changing the settings and hearing the tone change is incredible. It's funny that the noise has been with us for so long and now we can change it. What a fundamentally cool thing! It feels like this PR really touches the heart of the machine. Awesome work @blurfl!! You are really on fire here.

**Pull request merged**
