### PR TITLE
fix-feed-rate-limit-in-metric-mode

### PR DESCRIPTION
**Pull request by blurfl**
Previous version worked incorrectly when in metric mode

### CODE REVIEW

**Comment by BarbourSmith** [comment]
This one looks like it might have something wrong with it 😀 I'm seeing 24 files changed

**Comment by BarbourSmith** [comment]
Is it ok if I close this one? It's got all the file changes and it might be faster to just make a new PR with just the lines we want 👍

**Comment by blurfl** [comment]
Cancel and close this, it was handled in a separate PR

**Comment by BarbourSmith** [comment]
Does that mean it's done? I think there is still an issue out for it.

**Comment by blurfl** [comment]
I’ve gotta start reading these things on a larger screen :(

  This is not fixed.

**Comment by BarbourSmith** [comment]
😀

**Comment by blurfl** [comment]
I'll open a new PR. The fix I proposed was to dump the conversion and use the metric value. I tested in metric and inch mode, both work. Not elegant or pretty, but it corrects the problem behavior.

**Pull request closed without merging**
