### PR TITLE
Add integration with Travis-CI

### PR DESCRIPTION
**Pull request by idoc**
If the project is connected to Travis CI, it will detect any new commit and PR, and run a set of tests on it.

Right now, it just compiles the code for all supported boards (currently Ardumega and simavr, but I hear Teensy is in the works), and confirm that the code compiles. Once we have some automated tests in place, it can also run them.

Later on, this can also be used to automatically upload released binaries to GitHub, but I don't think we're there yet.

Once the build is done, Travis will update GitHub to show the status of PRs and branches. This is what it looks like in my forked project:
travis_ci_by_idoc_ _pull_request__1_ _idoc_firmware
and
branches_ _idoc_firmware

@BarbourSmith, I don't know if you have bandwidth to look at hooking up the main project to CI at this point, but I think this can be useful to merge for other contributors. With this in place, anybody can connect Travis to their forked projects with just a few clicks.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Beautiful!! This is amazing.

I would love to get Travis-CI integration set up, can you point me in the right direction as to where I would start clicking?

**Comment by idoc** [comment]
Happy to! It's actually easier and simpler than I imagined. I'll write up a mini-howto when I get home today.

**Comment by idoc** [comment]
K, here goes.

I don't intend this as a proper howto, just the shortest I can make it :)

	- Open http://travis-ci.org (not the .com, which is for closed-source projects)
	- Click "log in with GitHub". This lets Travis find all your repos and update their status.
	- Click on your icon on the top right corner, and click Profile.
	- You'll see a list of your repos at the bottom, all disabled by default. Enable Firmware.
	- Firmware already has a .travis.yml file, so Travis will know how build the code whenever there's need.
	- Aaaand you're done!

Whenever a PR or branch is created or updated, Travis will build it and add notes/icons to show what failed and what passed. People get emails on the status of their builds. You tweak notifications, connect it to Slack, and more.

Pass/fail notes are linked to build logs, so you can click and see the exact error. Their live-view build console is amazing.
	
AFAIR, this is all you need to do for basic functionality. There's more advanced stuff, like automatic releases, but I think that's all we really need right now.

Hope you like it! I'm glad to help any questions or need a hand.  I'm waaaay too happy to mess with this stuff (ask my coworkers).

**Comment by BarbourSmith** [comment]
Thanks!! That couldn't have been easier or more clear.

We should be up and running on the firmware 👍 👍 🎉 😀

**Comment by idoc** [comment]
Maybe a little :)

We haven't had a new PR or branch created since @BarbourSmith connected us to Travis. Once a PR is created and built by Travis, you'll see a status for that branch. Once the PR is merged to master, I expect you'll see the status applied to the master branch.

**Comment by blurfl** [comment]
Wouldn’t PR#405 show up? It was merged 8 hours ago...

**Comment by idoc** [comment]
It was created two days ago, though. To the best of my understanding of Travis, it's the push that trigger the build, not the merge. When you merge a PR, it just carries over the status of the build from the PR to the branch.

I just updated my #406 to trigger a Travis build, which passed. If you guys think it's OK to merge that change (it doesn't touch the firmware code, and Travis says it didn't break the PlatformIO build), we can merge it and see if it earns us a "passing" annotation on master.

**Comment by idoc** [comment]
Ooh! I just noticed this neat little touch.

When you're viewing a PR that's been tested by Travis, you get little status emblem on the favicon: image

**Comment by BarbourSmith** [comment]
This is great!

I think we needed to put a little bit of markdown in the readme to make the badge show up...so I did and it's there!

image

Can we run our builds for GC this way?

**Comment by idoc** [comment]
Linux and OS X: Probably, and I'm happy to give it a crack. Is there info on the GC wiki on how to build and package binaries? I'm not seeing anything.

I don't think there's anything we can do on Windows, though. Travis doesn't officially support, and, based on some googling, they don't plan to.

<fast forward through days and endless days of me complaining about Windows>

Even if we can't build all our official binaries, I can see it being useful for testing, though. Travis can make sure that the code is at least valid Python, and if/when we have some form of automated tests, it will be valuable to know that they pass on at least some of our supported OSs.

**Comment by BarbourSmith** [comment]
Darn, its a bummer we can't do windows too. 

The instructions for packaging for OS X are here: https://kivy.org/docs/guide/packaging-osx.html but @blurfl is our resident expert. 

If we are running a build on Linux it might be worth throwing in a package for Android. The serial connection thing hasn't been worked out yet, but having the package made every release might get the community excited about pushing in that direction

**Comment by blurfl** [comment]
The buildozer packaging puts python, Kivy and the extra packages into the package along with the GroundControl folder and some scripting to run things. It builds a .dmg file as the output.. Let me know how I can help.

**Comment by BarbourSmith** [comment]
Could I set up a windows server that would do the same thing? Having a fully automated build process would be pretty slick.

I'm looking forwards to playing around with this CI stuff as soon as I have a chance. I bet we can do a lot of fun things with it

**Comment by blurfl** [comment]
What's the Windows build process now? is Is scripted/scriptable?

**Comment by idoc** [comment]
I was about to ask the same thing.

I'm thinking if it's scriptable (and it [looks](https://kivy.org/docs/guide/packaging-windows.html) like it is), perhaps we can set up a [free Windows EC2 instance](https://aws.amazon.com/premiumsupport/knowledge-center/free-tier-windows-instance/) and have Travis SSH into it.

It will likely involve some futzing around, to see how the SSH private key can be stored securely and all that, and it won't be terribly fast, but I think we can make it work.

**Comment by BarbourSmith** [comment]
It is both script able and scripted. The "build.bat" file in the [build branch](https://github.com/MaslowCNC/GroundControl/tree/build) will run the whole process. 

I like the idea of using AWS a lot...great suggestion!

**Comment by blurfl** [comment]
I've got a script that uses the previous release of GC.dmg to build the new one, without buildozer. That might be easier to set up than the full buildozer/Kivy setup.

**Comment by BarbourSmith** [comment]
Woah!! Very cool @blurfl . I bet that is much quicker because most of the packaging is already done.

**Comment by idoc** [comment]
Oh nice! Looks like a lot of the scripting is already done, which will make my work a lot easier.

I'm going to ignore Windows for a bit, because it's the least convenient for me to work with (personal preference) and brings the most security concerns (need to open an EC2 machine to Travis, but not to Bitcoin miners and such).

Now that I think about it, @blurfl's GC-rebuilding script will need me to first download the latest release from GH into the Travis machine, won't it? I hope Travis lets me do that.

If the buildozer script is really just the `pip install` and then `buildozer osx debug`, maybe I'll start with that. It seems like the smallest number of things open questions, and will give us Linux, OS X, and Android. Once I get that to work, I can switch OS X to @blurfl's script to improve build time, and then start dealing with Windows and EC2.

Sounds sensible?

**Comment by blurfl** [comment]
It’s been a while since I went through the kivy install, I think there were some potholes in the road there. I’ve replaced icons in a couple places, but that’s just eye candy.

**Pull request merged**
