### PR TITLE
Added ability to change encoder steps, dist per revolution, and gear …

### PR DESCRIPTION
**Pull request by johnbenweber**
…radius from serial command.

I haven't had a chance to actually test this beside running it through the Arduino compiler without error. I'm not that familiar with the inner workings of Firmware so have a look and let me know if you see any potential issues. Corresponding GroundControl modifications to come.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Looks good. I don't see it causing issues with the rest of the firmware, but I'll test it anyway. We're going to run out of letters to send settings with soon 😄 

My only request for the Ground Control side is to maybe split the settings out into an "Advanced" section so we don't confuse everyone because most people won't want to mess with these settings.

**Comment by johnbenweber** [comment]
Yeah, we can always go to double letters if that becomes an issue.

**Comment by BarbourSmith** [comment]
Haha, yeah I'm not worried about it really. We can also split multiple commands if we need to.

**Comment by BarbourSmith** [comment]
I haven't forgotten about this one. I'm going to merge it soon. We've had some issues with circles coming out oval so I want to make sure I merge and test the other PR which messes with settings and things which touch the kinematics thoroughly so we can keep track of what is causing what.

**Comment by BarbourSmith** [comment]
I still haven't forgotten about this. I will test it and merge it today.

**Pull request merged**
