### PR TITLE
Use pullups to check board version, use #defines for version

### PR DESCRIPTION
**Pull request by blurfl**
Use pullups to check board version
use #defines for version
add two more version pins for future use, pull them up as well

### CODE REVIEW

**Comment by BarbourSmith** [comment]
This looks great!

I will test against all the board version in the morning and merge 🎉

**Comment by BarbourSmith** [comment]
Hmmm this seems to cause issues on 1.2 although I'm seeing version 1.2 be detected:

image

Any idea what might be going on or what else I can test?

**Comment by BarbourSmith** [comment]
Hang on, this looks to be an error on my part in the testing

**Comment by blurfl** [comment]
I must be dense, what is the issue? By all means use a different approach, this is just a quick stab at it. 🤗

**Comment by BarbourSmith** [comment]
> I must be dense, what is the issue? 

One of us is, but it's not you!

Ive been messing with the calibration stuff on my computer and I had it set up as top feed instead of bottom feed so everything was backwards 🙄 

Just tested again and all is well!! 👍 👍 🎉

**Comment by blurfl** [comment]
That’s good! I think I should leave preparing for the merging of the TLE5206 board to you, if that’s ok?

**Comment by BarbourSmith** [comment]
Do you mean moving the TLE5206 board into the /electronics repo?

**Comment by blurfl** [comment]
I meant firmware. While my PR will recognize the TLT5206 board, it does not add the defines needed to make it run. I figured that just doing the version part would be an appropriate 'baby step'.

**Comment by BarbourSmith** [comment]
OK, got it!

I'm making some progress on getting them made. They are a little weirded out by the whole we don't want any money thing but I think they will get it 😀

**Comment by blurfl** [comment]
>They are a little weirded out by the whole we don't want any money thing

I think you could sell them if you wanted, they're shared in the same way as the boards you currently sell, aren't they?

**Comment by BarbourSmith** [comment]
Its true and we will if we need to, but I think that if the factory can ship them direct it will be cheaper for everyone and they will be available sooner. We're really not that great at logistics 😀

**Pull request merged**
