### PR TITLE
Add support to the B02 function to extend only one or the other chain

### PR DESCRIPTION
**Pull request by BarbourSmith**
Which chain to extend is indicated with an L or R added to the line

Eg 'B02 L '

### CODE REVIEW

**Comment by krkeegan** [comment]
I don't know the proper best practices for gcode.  But is it common to just have a variable without a value trigger something?  Would L1 or R1 or Z1 be the better nomenclature?

**Comment by BarbourSmith** [comment]
That's a good question to raise.

I'm not sure. I think it's more clear with just the letter. Adding a number would make me as the question what the number means. I agree that it breaks with gcode convention

**Comment by krkeegan** [comment]
Just a thought, I don't think it matters enough to fight over it.  I came across the same problem in the PID B codes and opted to use a 1 to mean true.

**Comment by BarbourSmith** [comment]
You know the more I think about it the more I agree. I think that the correct behavior is that the command should always be 'B02 L1 R0' to just do one side. That way we have the option of moving more than one axis with a single command. Thanks for the pointer @krkeegan I will update the behavior

**Pull request merged**
