### PR TITLE
Add comments to document the board versioning system

### PR DESCRIPTION
**Pull request by blurfl**

### CODE REVIEW

**Comment by BarbourSmith** [comment]
Excellent documentation! I would thumbs up it three times if I could 👍 👍 👍

**Comment by davidelang** [comment]
Could you add the explination about how the pins are used on the different 
versions (the same explination that you gave me about why you needed the new 
board id because the different chip types use different ways of signalling 
direction, speed, and enable)

David Lang

**Comment by davidelang** [comment]
the code says which pins are input and output for each motor, but they don't 
describe the 'two pins to determine direction' vs 'one drection, one enable, 
either can be PWM' vs...

That's the type of info I think needs to appear in this file as well.

David Lang

**Comment by blurfl** [comment]
>but they don't describe the 'two pins to determine direction' vs 'one drection, one enable, either can be PWM' vs...

That's better handled by reading the data sheets for the respective ICs. The complexities go beyond what's appropriate in a firmware comment. That's where it is appropriate to read the fine manual.

**Comment by davidelang** [comment]
On Thu, 23 May 2019, Scott Smith wrote:

>> but they don't describe the 'two pins to determine direction' vs 'one drection, one enable, either can be PWM' vs...
>
> That's better handled by reading the data sheets for the respective ICs. The complexities go beyond what's appropriate in a firmware comment. That's where it is appropriate to read the fine manual.

in  that case, a link to the data sheets is appropriate (but I really thnk the 
simple explination you gave me would be good to have)

David Lang

**Comment by blurfl** [comment]
I'm going to close this for now, as there is ongoing discussion in Issue #504. Best to wait for that discussion to finish, then implement those decisions.

**Comment by BarbourSmith** [comment]
Ok, but if the discussion goes on too long and we need someone to just put their foot down, let me know. Ultimately I think having this new board exist is much more important than what version number it gets. I am really excited about this new chip. It is a very cool find.

**Comment by blurfl** [comment]
> this new chip

[Here](https://www.digikey.com/product-detail/en/infineon-technologies/HBRIDGEKIT2GOTOBO1/HBRIDGEKIT2GOTOBO1-ND/5878318) is the $15 development board for the chip. Very slick! [Here](https://www.infineon.com/dgdl/Infineon-H-Bridge_Kit_2Go_UM-UM-v01_01-EN.pdf?fileId=5546d46250cc1fdf015133ee879d3696&ack=t) the manual for the dev kit (software is free, but haven't tried it).

**Pull request closed without merging**
