### PR TITLE
Teensy project (for @blurfl)

### PR DESCRIPTION
**Pull request by idoc**
@blurfl Here's my take on a configurable setup. This will build the code for Teensy 3.5 and 3.6, but not attempt to upload it. To enable Teensy upload, set the TEENSY35_UPLOAD and/or TEENSY36_UPLOAD environment variable.

Currently, this can't be merged, because Maslow code doesn't build correctly for Teensy. But you can use this to play with configurable setups and add special compilation flags for your Teensy project.

If this works well for you, we can merge it once you get the code to compile with Teensy.

### CODE REVIEW

**Comment by blurfl** [comment]
Thank you very much! I'll give it a go first thing in the morning. I do have the code compiling and running Teensy3.5 and 3.6, though there are still some things to work on 😉.

**Comment by idoc** [comment]
Oh cool! I'm interested to see where this effort goes.

**Comment by BarbourSmith** [comment]
I was a fool and merged #399 before #400 which resulted in a couple conflicts. I took the #400 version for everything, but I wanted to mention it so that if there is an issue we know where the blame lies (with me!)

**Comment by idoc** [comment]
Um, sure! Yes. If anything breaks, be sure to blame @BarbourSmith. Definitely :)

(but do let me know it's broken, so I can upload a fix)

**Comment by blurfl** [comment]
Looks to me like all is well. A tangled web, github 😀

**Pull request merged**
