### PR TITLE
Add Bxx codes for heap inspection

### PR DESCRIPTION
**Pull request by blurfl**
B12 executes Avrheap.freeListWalk
B13 executes Avrheap.dumpHeap
Both require AvrHeap library from:
https://github.com/RobTillaart/Arduino/tree/master/libraries/AvrHeap

### CODE REVIEW

**Comment by blurfl** [comment]
These put heap info into the log. Unfortunately they didn't show anything that looked useful to my eyes - YMMV.

**Comment by BarbourSmith** [comment]
I'm going to take a look now.

Not seeing anything might just mean we're looking in the wrong place which would be valuable 👍 👍 👍

**Comment by BarbourSmith** [comment]
This is fantastic! I agree that I don't see any noticeable changes to he heap as the issue progresses, but it's so cool to be able to look at the heap directly and see how it changes. Great work!

**Comment by blurfl** [comment]
How about a BXX code to make changes to the PID values?

**Comment by BarbourSmith** [comment]
I like it. I also think you are spot on that the PID values are next place to look. By setting ` _Ki = 0` in MotorGearboxEncoder.h I was able to make the issue go away.

How do you feel about putting the option to change the PID values in the advanced settings instead of as a Bxx code?

**Comment by blurfl** [comment]
Very interesting! Advanced settings would be a good place for them.

**Comment by blurfl** [comment]
Thinking further about this, I think it would be good to include a “reset to default values” button in the same place. Explorers need an escape plan ☺️...

**Comment by BarbourSmith** [comment]
I've been thinking exactly the same thing! 😀 

I think I might make a forum thread to talk the idea through and get more opinions

**Pull request closed without merging**
